---
kind: pipeline
type: docker
name: web

steps:
- name: install
  image: node:14
  commands:
  - npm i --registry=https://registry.npm.taobao.org

- name: test
  image: node:14
  commands:
  - npm run playwright
