---
kind: pipeline
type: docker
name: web

steps:
- name: install
  image: node
  commands:
  - yarn

- name: test
  image: node
  commands:
  - yarn playwright

- name: build
  image: node
  commands:
  - npm run build

- name: rsync
  image: drillster/drone-rsync
  environment:
    RSYNC_KEY:
      from_secret: rsync_key
  settings:
    user: root
    hosts:
      - bugchao.com
    source: ./dist/*
    target: /usr/share/front-end
    secrets: [ rsync_key ]

