---
kind: pipeline
type: docker
name: web
volumes:
  - name: cache
    host: 
      path: /tmp/cache
steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
      - ./node_modules

- name: install
  image: node
  commands:
  - npm config set cache ./.npm-cache --global
  - npm install

- name: test
  image: node
  failure: ignore
  commands:
  - yarn playwright

- name: build
  image: node
  commands:
  - npm run build

- name: rsync
  image: drillster/drone-rsync
  environment:
    RSYNC_KEY:
      from_secret: rsync_key
  settings:
    user: root
    hosts:
      - bugchao.com
    source: ./dist/*
    target: /usr/share/front-end
    secrets: [ rsync_key ]

- name: notify
  image: lddsb/drone-dingtalk-message
  settings:
    token: da1643f55595bab854144f529a7df48a9f6cfbf509a2a7d285c76b7bb5543c13
    type: markdown
    secret: SEC9566f2ed09b21bcc4e373fc457bb38289b9da7347afdf66279f816d2d8c9f99a
  when:
    status:
    - failure
    - success

- name: rebuild-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    rebuild: true
    mount:
      - ./node_modules
